##############################################################
##############################################################
#######                Standard Variables              #######
##############################################################
##############################################################

variable "application_name" {
  description = "Project/application name. Must be lowercase alphanumeric characters and have a maximum length of 50 characters."
  nullable    = false
  sensitive   = false
  type        = string

  validation {
    condition     = length(var.application_name) <= 50 && can(regex("^[a-z0-9]*$", var.application_name))
    error_message = "The application_name must be lowercase alphanumeric characters and have a maximum length of 50 characters."
  }

}

variable "application_shortname" {
  description = "short version of project/application name. Must be lowercase alphanumeric characters and have a maximum length of 14 characters."
  nullable    = false
  sensitive   = false
  type        = string

  validation {
    condition     = length(var.application_shortname) <= 14 && can(regex("^[a-z0-9]*$", var.application_shortname))
    error_message = "The application_shortname must be lowercase alphanumeric characters and have a maximum length of 14 characters."
  }

}

variable "additional_tags" {
  default     = {}
  description = "Default map of tags to be applied to all resources generated by this module."
  nullable    = false
  sensitive   = false
  type        = map(string)
}

variable "environment_tag" {
  default     = "dev"
  description = "Environment tag e.g. dev, test, systest, UAT, Prod"
  nullable    = false
  sensitive   = false
  type        = string

  validation {
    condition     = can(regex("^(dev|poc|prod|uat|stg|sys)$", var.environment_tag))
    error_message = "Invalid environment tag. Allowed values are dev, uat, stg, sys, poc, and prod."
  }

}

##############################################################
##############################################################
#######        provider specific variables             #######
##############################################################
##############################################################
