#<!-- start_of_terraform_docs -->
# Service principal id
# azrm_client_id = ""

# # Service principal password
# azrm_client_secret = ""

# Azure subscription id
azrm_subscription_id = "subscription_id_dev"

# Default map of tags to be applied to all resources generated by this module.
additional_tags = {}

# Environment tag e.g. dev, test, systest, UAT, Prod
environment_tag = "dev"

# Number of years from now when keyvault secrets should expire
time_secret_expiry = 2

#<!-- end_of_terraform_docs -->
